apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: rotten-potatoes
build:
  artifacts:
  - image: rotten-potatoes
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/mongodb/deployment.yaml
    - k8s/mongodb/service.yaml
    - k8s/web/deployment.yaml
